export enum EProofmeDataPurpose {
    IDENTIFICATION = "IDENTIFICATION",
    AGE_VERIFICATION = "AGE_VERIFICATION",
    PROOFME_CONNECT = "PROOFME_CONNECT",
    KYC_VERIFICATION = "KYC_VERIFICATION",
    ACCESS_CONTROL = "ACCESS_CONTROL"
}