export enum IProofmeDataPurpose {
    AGE_VERIFICATION = "AGE_VERIFICATION",
    KYC_VERIFICATION = "KYC_VERIFICATION",
    ACCESS_CONTROL = "ACCESS_CONTROL",
    ONLINE_VERIFICATION = "ONLINE_VERIFICATION",
    IDENTIFICATION = "IDENTIFICATION"
}