export { SignalingServer } from "./signalingServer";
export { WebRtcProvider } from "./webRtc.provider";
export { ProofmeUtilsProvider } from "./proofme-utils.provider";
export { IRTCConnectionConfig } from "./interfaces/rtcConnectionConfig.interface";
export { IWebRTCConfig } from "./interfaces/webRtcConfig.interface";
export { calculateMinutesDifference } from "./functions/functions"
export { didContractKeyWrong } from "./functions/functions"
export { getKeyPurpose } from "./functions/functions"
export { getSha3Key } from "./functions/functions"
export { issuerCredentialSignatureWrong } from "./functions/functions"
export { knownAddressesContains } from "./functions/functions"
export { userCredentialSignatureWrong } from "./functions/functions"
export { validCredentialsFunc } from "./functions/functions"
export { signCredentialObject } from "./functions/functions"
export { signCredential } from "./functions/functions"
